@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### -------------------------------CATALOG----------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------


### ------------------------------------------------------------------------
# Get EAN inline
GET  {{server}}/catalog/getEAN(barcode=%277896061951343%27)
content-type: application/json




### Create Product
POST  {{server}}/catalog/Products
Accept: application/json
Content-Type: application/json

{ 
  "ID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960e",
  "EAN": "7894900011522",
  "productName": "Produto Test",
  "productDescription": "Desc produto",
  "brand": "Marca Produto" 
}

### Read Product
GET {{server}}/catalog/Products
Accept:  application//xml
Content-Type: application/xml

### Read Product with filter
GET {{server}}/catalog/Products?filter=(substringof(%27Lenco%27,productName)%20or%20substringof(%27Lenço%27,brand))

### Read product specific 
GET {{server}}/catalog/Products(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)




### Read Binary
GET {{server}}/catalog/Products(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)/imageContent

### Update Product
PUT  {{server}}/catalog/Products(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)
Accept: application/json
Content-Type: application/json

{ 
  "productDescription": "Desc produto alterado",
  "imageType": "image/pdf"
}

### Upload Binary
PUT {{server}}/catalog/Products(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)/imageContent
Content-Type: image/png

< ./Test.png



### Delete Product Content
DELETE {{server}}/catalog/Products(cf31b7df-51a6-47a2-a860-f6f0e1e1960e)/imageContent

### Delete Product 
DELETE {{server}}/catalog/Products(80d94aaa-f9e1-4ee5-81a7-b4ae58ff573a)


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ----------------------------CATALOG REST--------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------


### ------------------------------------------------------------------------
# Get EAN
GET  {{server}}/catalog-rest/getEAN
content-type: application/json
{{me}}

{ "barcode": "7896061951343"}

### ------------------------------------------------------------------------
# Get EAN inline
GET  {{server}}/catalog-rest/getEAN(barcode=7896061951343)
content-type: application/json
{{me}}



### Create Product
POST  {{server}}/catalog-rest/Products
Accept: application/json
Content-Type: application/json

{ 
  "ID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960a",
  "EAN": "7894900011530",
  "productName": "Produto Test",
  "productDescription": "Desc produto",
  "brand": "Marca Produto",
  "contentURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjWNMW/R8ABfwCjc2t99UAAAAASUVORK5CYII=" 
}

### Read Product
GET {{server}}/catalog-rest/Products


### Read Product with filter
GET {{server}}/catalog/Products?filter=(substringof(%27Lenco%27,productName)%20or%20substringof(%27Lenço%27,brand))


### Read product specific 
GET {{server}}/catalog-rest/Products/cf31b7df-51a6-47a2-a860-f6f0e1e1960e


### Read Binary
GET   {{server}}/catalog-rest/Products/cf31b7df-51a6-47a2-a860-f6f0e1e1960e/imageContent


### Create Product Image
POST  {{server}}/catalog-rest/postImageContent
Accept: application/json
Content-Type: application/json

{ 
  "ID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960e",
  "contentURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjWNMW/R8ABfwCjc2t99UAAAAASUVORK5CYII="
}

### Delete Product 
DELETE {{server}}/catalog-rest/Products/5f12027a-6f6b-426a-ade9-3fc2a6388f18



### Delete Product Content
POST {{server}}/catalog-rest/Products/cf31b7df-51a6-47a2-a860-f6f0e1e1960e/deleteImageContent

